"""empty message

Revision ID: 15d2a45950b7
Revises: 04999eb530cd
Create Date: 2019-07-04 22:32:01.052142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d2a45950b7'
down_revision = '04999eb530cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('first_n', sa.String(length=100), nullable=False))
    op.add_column('comment', sa.Column('last_n', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'last_n')
    op.drop_column('comment', 'first_n')
    # ### end Alembic commands ###
