"""empty message

Revision ID: 22c29be55dbc
Revises: aa8bc8fa11ab
Create Date: 2019-08-28 21:11:29.903844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c29be55dbc'
down_revision = 'aa8bc8fa11ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filename',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filename')
    # ### end Alembic commands ###
