"""empty message

Revision ID: 327d13c1dd23
Revises: 4471438b2cae
Create Date: 2019-08-30 20:36:56.870687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327d13c1dd23'
down_revision = '4471438b2cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('item_name', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###
