"""empty message

Revision ID: 46c4856d84dd
Revises: c7a74ae39a7a
Create Date: 2019-09-07 13:57:44.182728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c4856d84dd'
down_revision = 'c7a74ae39a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('one_vids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('onevidpath', sa.String(length=255), nullable=True),
    sa.Column('c_name', sa.String(length=255), nullable=True),
    sa.Column('vid_title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('one_vids')
    # ### end Alembic commands ###
