"""empty message

Revision ID: 67f19804d4b8
Revises: 34e55647ca49
Create Date: 2019-08-12 02:03:03.157111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67f19804d4b8'
down_revision = '34e55647ca49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ubookname', sa.String(length=150), nullable=False),
    sa.Column('uauthor', sa.String(length=150), nullable=False),
    sa.Column('uprice', sa.Integer(), nullable=True),
    sa.Column('uphotopath', sa.String(length=255), nullable=True),
    sa.Column('ustock_status', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('used_book')
    # ### end Alembic commands ###
