"""empty message

Revision ID: 7f587f2d5bcc
Revises: 90d1a25e17f4
Create Date: 2019-09-03 17:07:12.563496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f587f2d5bcc'
down_revision = '90d1a25e17f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.String(length=200), nullable=False),
    sa.Column('Orders_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Orders_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('custfname', sa.String(length=150), nullable=False))
    op.add_column('orders', sa.Column('custlname', sa.String(length=150), nullable=False))
    op.drop_column('orders', 'custname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('custname', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_column('orders', 'custlname')
    op.drop_column('orders', 'custfname')
    op.drop_table('order_content')
    # ### end Alembic commands ###
