"""empty message

Revision ID: 84026e36a111
Revises: 99572a13edbe
Create Date: 2019-06-26 19:02:41.390310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84026e36a111'
down_revision = '99572a13edbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'is_admin')
    # ### end Alembic commands ###
