"""empty message

Revision ID: 90d1a25e17f4
Revises: cd34c9059740
Create Date: 2019-09-01 15:11:04.011509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d1a25e17f4'
down_revision = 'cd34c9059740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('photopath', sa.String(length=255), nullable=True),
    sa.Column('stock_status', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('item_name', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('new_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookname', sa.String(length=150), nullable=False),
    sa.Column('publisher', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('photopath', sa.String(length=255), nullable=True),
    sa.Column('stock_status', sa.String(length=255), nullable=False),
    sa.Column('ISBN13', sa.String(length=255), nullable=False),
    sa.Column('ISBN10', sa.String(length=255), nullable=False),
    sa.Column('series', sa.String(length=255), nullable=False),
    sa.Column('Format', sa.String(length=255), nullable=False),
    sa.Column('publication_date', sa.String(length=255), nullable=False),
    sa.Column('dimensions', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('photopath', sa.String(length=255), nullable=True),
    sa.Column('stock_status', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('used_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ubookname', sa.String(length=150), nullable=False),
    sa.Column('uauthor', sa.String(length=150), nullable=False),
    sa.Column('uprice', sa.Integer(), nullable=True),
    sa.Column('uphotopath', sa.String(length=255), nullable=True),
    sa.Column('ustock_status', sa.String(length=255), nullable=False),
    sa.Column('uISBN13', sa.String(length=255), nullable=False),
    sa.Column('uISBN10', sa.String(length=255), nullable=False),
    sa.Column('uuseries', sa.String(length=255), nullable=False),
    sa.Column('uFormat', sa.String(length=255), nullable=False),
    sa.Column('upublication_date', sa.String(length=255), nullable=False),
    sa.Column('udimensions', sa.String(length=255), nullable=False),
    sa.Column('ulanguage', sa.String(length=255), nullable=False),
    sa.Column('uweight', sa.String(length=255), nullable=False),
    sa.Column('udescription', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('used_book')
    op.drop_table('supplies')
    op.drop_table('new_book')
    op.drop_table('cart')
    op.drop_table('accessories')
    # ### end Alembic commands ###
