"""empty message

Revision ID: 9ae387c9c3c9
Revises: 0748ffc77b82
Create Date: 2019-06-30 20:15:00.025386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae387c9c3c9'
down_revision = '0748ffc77b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('is_authorized', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'is_authorized')
    # ### end Alembic commands ###
