"""empty message

Revision ID: 9c2b28dcf63e
Revises: 46c4856d84dd
Create Date: 2019-09-08 14:01:57.700040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2b28dcf63e'
down_revision = '46c4856d84dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('two_vids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('onevidpath2', sa.String(length=255), nullable=True),
    sa.Column('c_name2', sa.String(length=255), nullable=True),
    sa.Column('vid_title2', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('two_vids')
    # ### end Alembic commands ###
