"""empty message

Revision ID: aa8bc8fa11ab
Revises: 8b32024bb88b
Create Date: 2019-08-28 17:38:46.083891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa8bc8fa11ab'
down_revision = '8b32024bb88b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('n_username', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'n_username')
    # ### end Alembic commands ###
