"""empty message

Revision ID: c7a74ae39a7a
Revises: f13d979f2ad3
Create Date: 2019-09-03 21:37:12.104015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a74ae39a7a'
down_revision = 'f13d979f2ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_content')
    op.add_column('Users', sa.Column('year', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('pay_option', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'pay_option')
    op.drop_column('Users', 'year')
    op.create_table('order_content',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('qty', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('Orders_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Orders_id'], ['orders.id'], name='order_content_Orders_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='order_content_pkey')
    )
    # ### end Alembic commands ###
